### ISSUE TITLE
Pre-submission check

### ISSUE THREAD

**Issue by bpbond** [ReScience/ten-years#11]
For [paper 33](https://github.com/ReScience/ten-years/issues/1#issuecomment-559936405) I have re-run the code and drafted a reproducibility report. Would someone mind taking a look? Anything major missing from your point of view? This was a fairly simple reproducibility challenge, and it actually worked 🎉 , so that kind of limits the length/detail.

Thank you!

[Paper 33 Reproducibility Report-12 Years Later….pdf](https://github.com/ReScience/ten-years/files/4259329/Paper.33.Reproducibility.Report-12.Years.Later.pdf)

P.S. repository is [here](https://github.com/bpbond/ten-years-paper33).

**Comment by rougier** [comment]
Results are impressive actually, only a tiny difference. Any idea where it comes from ?
For the actual article, you're free to extend your report and anlysis. I think the conclusion is really interesting (R core vs tidyverse) and could be extended a bit (because this is precisely the things we want to know).

For the article, you can also have a look at [current submissions](https://github.com/ReScience/submissions/issues?utf8=%E2%9C%93&q=is%3Aissue++label%3A%22Ten+Years+Challenge%22+) to check if you forgot something.

**Comment by bpbond** [comment]
Thanks for the deadline extension. [Submitted](https://github.com/ReScience/submissions/issues/40). I didn't use the ReScience template but happy to do that down the road.
